#!/bin/sh

COMMAND=`basename "$0"`
WORKING_DIR="/app"
DOCKER_CMD='docker run --rm'

if [ -f "$PWD/.env" ]
then
    DOCKER_CMD=$DOCKER_CMD" --env-file $PWD/.env"
fi
DOCKER_CMD=$DOCKER_CMD" -i \
    --network=host \
    -v $HOME:$HOME:ro \
    -v $PWD/wp-src:/var/www/html \
    -v $PWD/wp-content:/var/www/html/wp-content \
    -v /tmp:/tmp \
    -v $PWD:$WORKING_DIR \
    -v $HOME/.composer:$HOME/.composer \
    -u $(id -u):$(id -g) \
    -w $WORKING_DIR \
    mfdeveloper/wordpress-tools:latest \
    $COMMAND $@"

eval $DOCKER_CMD

exit $?