#!/bin/sh

COMMAND=`basename "$0"`
docker run \
    --rm \
    -it \
    --env-file ./.env \
    --network=host \
    -v "$PWD/wp-src":"/var/www/html" \
    -v "$PWD/wp-content":"/var/www/html/wp-content" \
    -v /tmp:/tmp \
    -v $PWD:/app \
    -v "$HOME/.composer":"$HOME/.composer" \
    -u $(id -u):$(id -g) \
    -w /app \
    mfdeveloper/wordpress-tools:latest \
    $COMMAND "$@"

exit $?