#!/bin/sh
tty=
tty -s && tty=--tty

DOCKER_CMD="docker run $tty -i --rm"
if [ -f "$PWD/.env" ]
then
    DOCKER_CMD=$DOCKER_CMD" --env-file $PWD/.env"
fi
DOCKER_CMD=$DOCKER_CMD" -i \
    --network=host \
    -v $HOME:$HOME:ro \
    -u $(id -u) \
    -w $PWD \
    php:7.2-alpine $@"

eval $DOCKER_CMD
exit $?
